# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Salesforce Industries Journey To Employment
tagline:             ''
description:         ''
url:                 /Journey2Employment
baseurl:             /Journey2Employment

# About/contact
author:
  name:              Industries Team
  email:             gdendukuri@salesforce.com
  email:             saksham.agarwal@salesforce.com
  email:             ankita.bansal@salesforce.com

#Sidebar
github:
  repo               https://github.com/salesforce-vto/Journey2Employment

# Custom vars
version:             1.0.0
usefulLinks:             /usefulLinks
contributors:           /contributors

theme: jekyll-theme-minimal